#
# spring configuration
#
server:
  port: 80

spring:
  application:
    name: Joshua

  datasource:
    url: jdbc:mysql://localhost:3306/gyt
    username: gyt
    password: gyt
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  messages:
    basename: i18n/messages

#
# loggin configuration
#
logging.level.org.springframework: ERROR
logging.level.org.springframework.web: ERROR
logging.level.org.hibernate: ERROR
logging.level.org.gyt.web: DEBUG
logging:
  file: /var/opt/log/gyt/web/joshua.log